'use client';

import { format } from 'date-fns';

interface SynthesisViewProps {
  synthesis: {
    headline: string;
    highlights: string[];
    model: string;
    created_at: string;
  };
}

export function SynthesisView({ synthesis }: SynthesisViewProps) {
  return (
    <div className="flex flex-col gap-2">
      <h4 className="font-[family-name:var(--font-serif)] text-lg font-semibold text-[#1A1A1A] dark:text-[#E8E6E3]">
        {synthesis.headline}
      </h4>

      <div className="w-8 h-px bg-[#E8E5E0] dark:bg-stone-700 my-3" />

      <ul className="space-y-3">
        {synthesis.highlights.map((highlight, i) => (
          <li key={i} className="flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 flex-shrink-0" />
            <p className="font-[family-name:var(--font-serif)] text-sm text-stone-600 dark:text-stone-300 leading-relaxed">
              {highlight}
            </p>
          </li>
        ))}
      </ul>

      <div className="mt-4 pt-3 border-t border-[#E8E5E0] dark:border-stone-800">
        <p className="text-xs text-stone-400">
          Generated by {synthesis.model} &middot;{' '}
          {format(new Date(synthesis.created_at), 'MMM d, yyyy h:mm a')}
        </p>
      </div>
    </div>
  );
}
