'use client';

import { format } from 'date-fns';
import type { Synthesis } from '@/lib/types';

interface SynthesisViewProps {
  synthesis: Synthesis;
}

export function SynthesisView({ synthesis }: SynthesisViewProps) {
  return (
    <div className="flex flex-col gap-2">
      {/* Headline */}
      <h4 className="text-lg font-semibold text-stone-800 dark:text-stone-100">
        {synthesis.headline}
      </h4>

      {/* Divider */}
      <div className="w-8 h-px bg-stone-200 dark:bg-stone-700 my-3" />

      {/* Highlights */}
      <ul className="space-y-3">
        {synthesis.highlights.map((highlight, i) => (
          <li key={i} className="flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 flex-shrink-0" />
            <p className="text-sm text-stone-600 dark:text-stone-300 leading-relaxed">
              {highlight}
            </p>
          </li>
        ))}
      </ul>

      {/* Metadata footer */}
      <div className="mt-4 pt-3 border-t border-stone-100 dark:border-stone-800">
        <p className="text-xs text-stone-400">
          Generated by {synthesis.model} &middot;{' '}
          {format(new Date(synthesis.createdAt), 'MMM d, yyyy h:mm a')}
        </p>
      </div>
    </div>
  );
}
